service: cat-factory

frameworkVersion: "2"
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    CAT_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.CAT_TABLE}"

resources:
  Resources:
    CatTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.CAT_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

functions:
  getCats:
    handler: handlers/getCats.handler
    events:
      - http:
          method: GET
          path: cat
  getCat:
    handler: handlers/getCat.handler
    events:
      - http:
          method: GET
          path: cat/{id}
  createCat:
    handler: handlers/createCat.handler
    events:
      - http:
          method: POST
          path: cat
  deleteCat:
    handler: handlers/deleteCat.handler
    events:
      - http:
          method: DELETE
          path: cat/{id}

custom:
  bundle:
    esbuild: true
