service: cat-factory

frameworkVersion: "2"
plugins:
  - serverless-bundle

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    CAT_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    CAT_BUCKET_NAME: ${self:custom.CatBucket.name}
  iamRoleStatements:
    - ${file(iams/CatTableIAM.yml):CatTableIAM}
    - ${file(iams/CatBucketIAM.yml):CatBucketIAM}

resources:
  Resources:
    CatTable: ${file(resources/CatTable.yml):CatTable}
    CatBucket: ${file(resources/CatBucket.yml):CatBucket}
    CatBucketPolicy: ${file(resources/CatBucket.yml):CatBucketPolicy}

functions:
  getCats:
    handler: handlers/getCats.handler
    events:
      - http:
          method: GET
          path: cat
  getCat:
    handler: handlers/getCat.handler
    events:
      - http:
          method: GET
          path: cat/{id}
  createCat:
    handler: handlers/createCat.handler
    events:
      - http:
          method: POST
          path: cat
  deleteCat:
    handler: handlers/deleteCat.handler
    events:
      - http:
          method: DELETE
          path: cat/{id}

  updateCat:
    handler: handlers/updateCat.handler
    events:
      - http:
          method: PUT
          path: cat/{id}

custom:
  bundle:
    esbuild: true
  CatBucket:
    name: cats-bucket-xsql-${opt:stage, self:provider.stage}
